name = "Ky's Create Server Pack"
author = "ky7969"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5fe5a03ae37f34989bf383113c668ced9724b61c023cda40990a5a3c3b42ba3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
