name = "Ky's Create Server Pack"
author = "ky7969"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0d0067f95dfccc50faae9324db4ca53965701189d9818fc8b0eae44a3802904"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
