name = "Ky's Create Server Pack"
author = "ky7969"
version = "1.31"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "875f7fe21e22e3b3ccb274867e2c3fe4767e346cd41975144fa0892c2c52073e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
