name = "Ky's Create Server Pack"
author = "ky7969"
version = "1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a12b566db2019c9bf6340291742eed153e1a49ba2153989105a69aeb2d07d0b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
