name: Create Zip on Push

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip Folder
        run: zip -r "Ky's Create Pack.zip" . "/Ky's Create Pack/"

      - name: Upload Zip
        uses: actions/upload-artifact@v4
        with:
          name: latest-zip-package
          path: repository_export.zip
